/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CurrenciesDropdown {
        "changeCurrency": Function;
    }
    interface CurrencyConvertor {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLCurrenciesDropdownElement extends Components.CurrenciesDropdown, HTMLStencilElement {
    }
    var HTMLCurrenciesDropdownElement: {
        prototype: HTMLCurrenciesDropdownElement;
        new (): HTMLCurrenciesDropdownElement;
    };
    interface HTMLCurrencyConvertorElement extends Components.CurrencyConvertor, HTMLStencilElement {
    }
    var HTMLCurrencyConvertorElement: {
        prototype: HTMLCurrencyConvertorElement;
        new (): HTMLCurrencyConvertorElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "currencies-dropdown": HTMLCurrenciesDropdownElement;
        "currency-convertor": HTMLCurrencyConvertorElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CurrenciesDropdown {
        "changeCurrency"?: Function;
    }
    interface CurrencyConvertor {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "currencies-dropdown": CurrenciesDropdown;
        "currency-convertor": CurrencyConvertor;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "currencies-dropdown": LocalJSX.CurrenciesDropdown & JSXBase.HTMLAttributes<HTMLCurrenciesDropdownElement>;
            "currency-convertor": LocalJSX.CurrencyConvertor & JSXBase.HTMLAttributes<HTMLCurrencyConvertorElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
